CREATE TABLE PAYMENT (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nombre VARCHAR(255) NOT NULL,
	apellidos VARCHAR(255) NOT NULL,
	tipo_documento VARCHAR(3) NOT NULL,
	numero_documento VARCHAR(12) NOT NULL,
	referencia VARCHAR(255) NOT NULL,
	transaccion VARCHAR(255) NOT NULL,
	fecha_transaccion TIMESTAMP NOT NULL,
	estado VARCHAR(255) NOT NULL
);

CREATE SEQUENCE payment_sequence start with 1 increment by 1;